version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:30"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
